:PROPERTIES:
:ID:       c70e46ae-17dd-4ef6-ac8c-962c2f0373e1
:END:
#+title: unscrewing your life
:PROPERTIES:
:ID:       aa04c9f7-e6f2-4a75-b4c9-86e34782d62b
:END:

#writing #projects
[[id:a89bfedb-6db7-4264-a81a-4a584658355a][projects]]
* PRA FAZER adicionar os conteúdos do org file aqui
* advise people to seek professional help
write something like that this isn't a substitute for therapy, that
i'm not a therapist and i won't give any guarantees.
* PRA FAZER [#A] I need to come up with a method to write about topics
** which basic questions I have to answer on each topic
*** why

*** how

*** what to do after
as in how to recurr on this process

** parts

*** observation
reflection of the self on fiction and observing

*** overcoming
chiseling off the bad parts 

* license
gpl v2
depois preciso copiar e colar aqui
* favoritos do chrome
** PRA FAZER [#A] tem uma lista com umas coisas de biblioterapia
agora estou com muita dor de cabeça mas depois é pra eu dar uma olahda
* some remarks
when the individual is confronted by the depletion of perceived
possibilities in life and feels cornered by reality. As in they feel
unable to conceive any meaning out of his surroundings


** say something about craving for control
and any frustration that might come of out of it.

** this duality of what is to be and what is ought to be, as in the will of the individual and his conception of his possibilities. 
I think I need to think better about this

** one must
get back into means of being and getting reattached to reality. To
regain the reins of its own life. First, one must investigate what is
hindering him from doint it.

** what reality is composed of or our perception of reality and how do we put meaning into it

*** time itself is a fundamental concept
if all days feels the same, one doesn't have control of its own
time. It doesn't matter if he is achieving anything else in life. Time
is perceived through novelty and meaningful experiences. 

Epicureanism is great at this, because when one is able to maximize
pleasure out of mundane experiences each one of those turn into time
marks that they can situate themselves.
**** whatever novelty and meaning are to the person in question
this can be achieved through means of art, writing is an easy way to
get back into reality. And the therapeutic 

*** love also seems important
this is basically the social aspect of life. Forming bonds with other people
**** romantic partners

**** family

**** friends

**** pets?

*** making things that will remain in some way

**** children

**** planting trees 

**** building things

*** sense of belonging

** ways out of it

*** suicide
this is to abdicate any possibility of change. Which is the coward's
way out, unless it is to achieve some kind of meaning as in
martyrdom. But one must never strive for it, because when one's crave
for death it is definitely bound to poor meanings to be conceived and
will be remembered as a fool. As in one must be confronted with the
possibility of death before considering instead of running straight
into it.

*** denying reality itself i.e. madman's way out, drugs, whatever else
This is pure waste of time, worse than innaction depending on the
approach used. As the mind itself is subject to deterioration if it
isn't mainteined properly.

**** quote aristotle and some other bs stuff on this kind of stuff

*** reconstructing one's own reality by experience 
This is Nietzsche's way out ot if. Remaking reality through will and
to overcome the nihilism. Art is a decent mean of doing it.

*** religion
This is the common approach, most people do it. It involves all things
mentione on the what reality is composed of, and it is the easiest way
out of this.

* so you want to fix your brain
name change
- examined life
- Literature: The Mirror of Soul
  Literatura: o espelho da alma


this is an invite to the read to examine his life through reading
fiction

why this matters? 
because reading fiction creates the distance needed for people to look at
their own dark sides. 

seeing on others what we are too scared to see in ourselves.
talk about the Freudian view of traumatic remembrances. 

talk about the medusa myth, nietzsche

how this is similar to seeing a friend in a situation and what we
think about the fiction might help us think about our own lives.

being exposed to dormant traumas

not sure if this is the best name possible either. Because the
proposition is about constructing a self around fiction. Dealing with
traumas but also maturing and growing. So it is not plain observation
of the self. The observation is part of the process.
** the examined life
quote that Kafka ouroboros thing
this comes from kafka's diaries
*** introduction
quote Socrates
** do you want to change?
*** think about your motivations
**** why do you think there is something wrong with you?

***** PRA FAZER [#A] explain how self-image is and how it works
brief explanation

***** explain what would you say to a friend if he felt like that
***** confirm that with your friends/family
to reduce biases
think about a method for people with messed up family

**** why do you want to change?


*** what you can possibly change

**** dunno what i improved so far
need to think about this

**** PRA FAZER [#B] list things that can be improved
limit it to "light" things
pesquisar sobre biblioterapia? e ver no que ela funciona bem

no livro de cbt da judith acho que tem alguma coisa sobre ler livros
com personagens que também passam pelos mesmos problemas que a gente.
***** empathy

***** anger issues

***** 
** how to pick a book?
Picking the right book for this kind of reading isn't that
complicated. You can start doing it with short stories and religious
texts. They are a decent start for when you don't have any idea of
what is wrong you.

Escolher o livro certo para este tipo de leitura não é tão complicado
assim. Dá para começar com livros de contos e textos religiosos. Eles
são um bom começo se você não tem ideia do que está errado com você.


** read paying attention to your own emotions
**** PRA FAZER lista de livros por tipo de sentimento perguntar/pesquisar
***** reddit
****** feelings
******* anger
******* love
******* anxiety
******* fear
******* guilt
******* embarrassment
******* shame
******* relief
******* contempt
******* disgust
******* paranoia

***** 4chan
****** feelings
******* love
******** crossing to safety
wallace stegner
******** this is how you lost her
junot diaz
******** pride and prejudice, persuasion
jane austen
******** legends of the fall
jim harrison
******** chilly scenes of winter
ann beattie
******** spring snow
yukio mishima
******** the history of love
nicole krauss
******** love in the time of cholera
gcm
******** the unbearable lightness of being
milan kundera
******** normal people
sally rooney

***** goodreads
***** skoob


*** you have to start somewhere
If you don't have any problems with any particular emotion. This order
might seem ok.
**** arousal erotic literature is a good start if you are underdeveloped
it is easy to identify when we are aroused by something
probably any erotic novel will do, but I might get suggestions on
books with mixed emotions so it is not only arousal.

Might want to quote Freud on this one.
**** something that makes you nervous or anxious fearful
need to think about this, but probably horror/mistery/thrillers
**** anger

characters being jerks with another character you relate to?

***** kinda like saikano shuuji being a jerk to chise
**** paranoia
strindberg the battle of the brains
this can be caused by a constant search for stimulus 
if people enjoy "battling" too much they'll be brain exhausted

**** surprise

**** guilt

***** kierkegaard either/or

**** amusement

**** embarrassment / shame

**** relief

**** contempt

**** disgust
almost forgot this one. 

violence?

weak being abused? animals or children

scatological?


**** books that make you happy
any happy stories with good endings

love in the time of cholera


**** books that make you sad
depressing things, 
***** PRA FAZER lembrar para ter um cuidado extra com estes tipos

*** ideally books set on the same epoch you lived
this is because it is easier to relate to protagonists. If you have
been through a particular hard period in your life, they are probably
the best way to start, but I'm not sure on this one.
**** childhood

**** teenage

**** adulthood

** look for abnormal patterns
abnormal is a dangerous word

*** for mature readers only, I might not put it though. 
this is probably too hard to do and I'll probably not put it

This can also be related to feeling things out of the perceived author
intent with a passage or book. Or anything distant from other people's
impressions on it. 

*** any reaction out of the "ordinary" to anything you read

**** PRA FAZER preciso pensar em exemplos neutros

****  examples

***** first
You like cats. Read something about a cat having kitties and feel sad.

****** seems strange, right?

***** second

***** third

***** fourth

***** fifth
*** or the absence of a reaction to an extreme situation
those can be related to some other things like
**** desensitization due to exposure
self explanatory but i'll explain it later
**** something repressed

** after each reaction 
Find for the source of it. They can be caused by specific words,
actions, places, dialogues. This is a fundamental step to uncover
whatever is messin with you.



** show your "patterns" to someone else and ask if they seem ok
*** if they seem ok 
**** great
*** even better if they aren't
**** probably related to something you uncovered
***** now you work on it

